Import('rtconfig')
from building import *

cwd = GetCurrentDir()
path = [cwd + '/CMSIS/Core/Include',
        cwd + '/CMSIS/Core/m-profile',
        cwd + '/MIMXRT1189', 
        cwd + '/MIMXRT1189/drivers', 
        cwd + '/MIMXRT1189/periph']
src = Split('''
            MIMXRT1189/drivers/fsl_common.c
            MIMXRT1189/drivers/fsl_common_arm.c
            MIMXRT1189/drivers/fsl_dcdc.c
            MIMXRT1189/drivers/fsl_pmu.c
            MIMXRT1189/drivers/fsl_clock.c
            MIMXRT1189/drivers/fsl_ele_base_api.c
            MIMXRT1189/drivers/fsl_s3mu.c
            MIMXRT1189/drivers/fsl_trdc.c
            MIMXRT1189/drivers/fsl_gpc.c
            MIMXRT1189/drivers/fsl_memory.c           
            MIMXRT1189/drivers/fsl_soc_src.c
            ''')

if GetDepend(['BSP_USING_DMA']):
    src += ['MIMXRT1189/drivers/fsl_edma.c']
    src += ['MIMXRT1189/drivers/fsl_edma_soc.c']

if GetDepend(['SOC_MIMXRT1189CVM8C_CM33']):
    path += [cwd + '/MIMXRT1189/drivers/cm33']
    src += ['MIMXRT1189/system_MIMXRT1189_cm33.c']
    src += ['MIMXRT1189/drivers/cm33/fsl_cache.c']
    if rtconfig.PLATFORM in ['gcc']:
        src += ['MIMXRT1189/gcc/startup_MIMXRT1189_cm33.S']
    elif rtconfig.PLATFORM in ['armcc', 'armclang']:
        src += ['MIMXRT1189/arm/startup_MIMXRT1189_cm33.s']
    elif rtconfig.PLATFORM in ['iccarm']:
        src += ['MIMXRT1189/iar/startup_MIMXRT1189_cm33.s']

if GetDepend(['SOC_MIMXRT1189CVM8C_CM7']):
    path += [cwd + '/MIMXRT1189/drivers/cm7']
    src += ['MIMXRT1189/system_MIMXRT1189_cm7.c']
    src += ['MIMXRT1189/drivers/cm7/fsl_cache.c']
    if rtconfig.PLATFORM in ['gcc']:
        src += ['MIMXRT1189/gcc/startup_MIMXRT1189_cm7.S']
    elif rtconfig.PLATFORM in ['armcc', 'armclang']:
        src += ['MIMXRT1189/arm/startup_MIMXRT1189_cm7.s']
    elif rtconfig.PLATFORM in ['iccarm']:
        src += ['MIMXRT1189/iar/startup_MIMXRT1189_cm7.s']

if GetDepend(['BSP_USING_GPIO']):
    src += ['MIMXRT1189/drivers/fsl_rgpio.c']

if GetDepend(['BSP_USING_LPUART']):
    src += ['MIMXRT1189/drivers/fsl_lpuart.c']
    if GetDepend(['BSP_USING_DMA']):
        src += ['MIMXRT1189/drivers/fsl_lpuart_edma.c']

if GetDepend(['BSP_USING_CLOCK_TIMER']):
    src += ['MIMXRT1189/drivers/fsl_gpt.c']

if GetDepend(['BSP_USING_I2C']):
    src += ['MIMXRT1189/drivers/fsl_lpi2c.c']
    if GetDepend(['BSP_USING_DMA']):
        src += ['MIMXRT1189/drivers/fsl_lpi2c_edma.c']    

if GetDepend(['BSP_USING_SPI']):
    src += ['MIMXRT1189/drivers/fsl_lpspi.c']
    if GetDepend(['BSP_USING_DMA']):
        src += ['MIMXRT1189/drivers/fsl_lpspi_edma.c']

if GetDepend(['RT_USING_CAN']):
    src += ['MIMXRT1189/drivers/fsl_flexcan.c']

if GetDepend(['BSP_USING_FLEXSPI']):
    src += ['MIMXRT1189/drivers/fsl_flexspi.c']
    if GetDepend(['BSP_USING_DMA']):
        src += ['MIMXRT1189/drivers/fsl_flexspi_edma.c']    

if GetDepend(['BSP_USING_SDIO']):
    src += ['MIMXRT1189/drivers/fsl_usdhc.c']

if GetDepend(['BSP_USING_LPADC']):
    src += ['MIMXRT1189/drivers/fsl_lpadc.c']

if GetDepend(['BSP_USE_MULTICORE']):
    src += ['MIMXRT1189/drivers/fsl_mu.c']
    src += [
        'multicore/mcmgr/src/mcmgr.c',
        'multicore/mcmgr/src/mcmgr_internal_core_api_imxrt1180.c',
        'multicore/mcmgr/src/mcmgr_mu_internal.c',
    ]
    path += [
        cwd + '/multicore/mcmgr/inc',
        cwd + '/multicore/mcmgr/inc/platform/imxrt1180',
    ]

if GetDepend(['BSP_USE_MULTICORE_RPMSG_LITE']):
    src += [
        'multicore/rpmsg-lite/lib/common/llist.c',
        'multicore/rpmsg-lite/lib/rpmsg_lite/rpmsg_lite.c',
        'multicore/rpmsg-lite/lib/rpmsg_lite/rpmsg_queue.c',
        'multicore/rpmsg-lite/lib/rpmsg_lite/rpmsg_ns.c',
        'multicore/rpmsg-lite/lib/virtio/virtqueue.c',
        'multicore/rpmsg-lite/lib/rpmsg_lite/porting/environment/rpmsg_env_rtthread.c',
        'multicore/rpmsg-lite/lib/rpmsg_lite/porting/platform/imxrt1180/rpmsg_platform.c',
    ]
    path += [
        cwd + '/multicore/rpmsg-lite/lib/include',
        cwd + '/multicore/rpmsg-lite/lib/include/environment/rtthread',
        cwd + '/multicore/rpmsg-lite/lib/include/platform/imxrt1180',
    ]

if GetDepend(['BSP_USING_ETH']):
    src += [
        'MIMXRT1189/drivers/fsl_msgintr.c',
        'MIMXRT1189/drivers/fsl_netc_ierb.c',
        'MIMXRT1189/drivers/fsl_netc_timer.c',
        'MIMXRT1189/drivers/fsl_netc_mdio.c',
        'MIMXRT1189/drivers/fsl_netc_endpoint.c',
        'MIMXRT1189/drivers/fsl_netc_soc.c',
        'MIMXRT1189/drivers/netc_hw/fsl_netc_hw.c',
        'MIMXRT1189/drivers/netc_hw/fsl_netc_hw_port.c',
        'MIMXRT1189/drivers/netc_hw/fsl_netc_hw_si.c',
        'MIMXRT1189/drivers/netc_hw/fsl_netc_hw_enetc.c',
    ]
    if str(GetDepend('NETC_USE_SWT')) == '1':
        src += ['MIMXRT1189/drivers/fsl_netc_switch.c']

if GetDepend(['BSP_USING_ETHERCAT']):
    src += [
        'MIMXRT1189/drivers/fsl_gpt.c',
        'MIMXRT1189/drivers/fsl_ecat.c',
        'MIMXRT1189/drivers/fsl_xbar.c',
        'ethercat/ethercat_init.c',
        'ethercat/digital_io.c',
    ]
    src += Glob(cwd + '/ethercat/SSC/Src/*.c')
    path += [
        cwd + '/ethercat',
        cwd + '/ethercat/SSC/Src',
    ]

#fsl os abstract files
# src += ['MIMXRT1189/drivers/fsl_os_abstraction_rtthread.c']
# src += ['MIMXRT1189/drivers/generic_list.c']

if rtconfig.PLATFORM in ['gcc']:
    group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path, ASFLAGS = '$ASFLAGS -D __STARTUP_CLEAR_BSS')
else:
    group = DefineGroup('Libraries', src, depend = [''], CPPPATH = path)

Return('group')
